package main

import (
	"archive/zip"
	"database/sql"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

const libraryExportFormatVersion = 1

type libraryExportManifest struct {
	Format                 string    `json:"format"`
	FormatVersion          int       `json:"formatVersion"`
	ExportedAt             time.Time `json:"exportedAt"`
	DatabaseVersion        int       `json:"databaseVersion"`
	MediaIncluded          bool      `json:"mediaIncluded"`
	ContainsPrivateDB      bool      `json:"containsPrivateDatabaseState"`
	QuarantinedRecordCount int       `json:"quarantinedRecordCount"`
}

type libraryExportDocument struct {
	Manifest libraryExportManifest `json:"manifest"`
	Records  []libraryExportRecord `json:"records"`
}

type libraryExportRecord struct {
	JobID     string            `json:"jobId"`
	URL       string            `json:"url"`
	Kind      string            `json:"kind"`
	MediaType string            `json:"mediaType"`
	Status    string            `json:"status"`
	Title     string            `json:"title"`
	CreatedAt string            `json:"createdAt"`
	Category  string            `json:"category,omitempty"`
	File      libraryExportFile `json:"file"`
}

type libraryExportFile struct {
	ID                 string                 `json:"id"`
	Name               string                 `json:"name"`
	Size               int64                  `json:"size"`
	Height             int                    `json:"height,omitempty"`
	MimeType           string                 `json:"mimeType"`
	Title              string                 `json:"title,omitempty"`
	Author             string                 `json:"author,omitempty"`
	DurationSeconds    int64                  `json:"durationSeconds,omitempty"`
	ThumbnailURL       string                 `json:"thumbnailUrl,omitempty"`
	PublishDate        string                 `json:"publishDate,omitempty"`
	Category           string                 `json:"category,omitempty"`
	OutputRelativePath string                 `json:"outputRelativePath,omitempty"`
	ManagedAvailable   bool                   `json:"managedAvailable"`
	PublishedAvailable bool                   `json:"publishedAvailable"`
	Subtitle           *libraryExportSubtitle `json:"subtitle,omitempty"`
	Chapters           []mediaChapter         `json:"chapters,omitempty"`
	SourceItemIndex    int                    `json:"sourceItemIndex,omitempty"`
	ChapterIndex       int                    `json:"chapterIndex,omitempty"`
	ChapterTitle       string                 `json:"chapterTitle,omitempty"`
}

type libraryExportSubtitle struct {
	LanguageCode       string `json:"languageCode"`
	Label              string `json:"label,omitempty"`
	Format             string `json:"format"`
	AutoGenerated      bool   `json:"autoGenerated,omitempty"`
	Name               string `json:"name"`
	Size               int64  `json:"size"`
	OutputRelativePath string `json:"outputRelativePath,omitempty"`
	ManagedAvailable   bool   `json:"managedAvailable"`
	PublishedAvailable bool   `json:"publishedAvailable"`
}

func (s *server) handleLibraryExport(w http.ResponseWriter, r *http.Request) {
	archivePath, cleanup, err := s.createLibraryExport()
	if err != nil {
		fail(w, http.StatusInternalServerError, "Could not export the Library")
		return
	}
	defer cleanup()
	w.Header().Set("Content-Type", "application/zip")
	w.Header().Set("Content-Disposition", `attachment; filename="yt-dl-go-library-export.zip"`)
	http.ServeFile(w, r, archivePath)
}

func (s *server) createLibraryExport() (string, func(), error) {
	workDir, err := os.MkdirTemp(s.cfg.root, ".library-export-")
	if err != nil {
		return "", nil, fmt.Errorf("create private export workspace: %w", err)
	}
	cleanup := func() { _ = os.RemoveAll(workDir) }
	if err := os.Chmod(workDir, 0700); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("restrict export workspace: %w", err)
	}

	databasePath := filepath.Join(workDir, "state.db")
	quotedDatabasePath := "'" + strings.ReplaceAll(databasePath, "'", "''") + "'"
	if _, err := s.store.db.Exec(`VACUUM INTO ` + quotedDatabasePath); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("create consistent database snapshot: %w", err)
	}
	if err := os.Chmod(databasePath, 0600); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("restrict database snapshot: %w", err)
	}

	dsn, err := sqliteReadOnlyDSN(databasePath)
	if err != nil {
		cleanup()
		return "", nil, err
	}
	database, err := sql.Open("sqlite", dsn)
	if err != nil {
		cleanup()
		return "", nil, fmt.Errorf("open database snapshot: %w", err)
	}
	database.SetMaxOpenConns(1)
	if err := checkDatabaseIntegrity(database); err != nil {
		_ = database.Close()
		cleanup()
		return "", nil, fmt.Errorf("check exported database snapshot: %w", err)
	}
	var databaseVersion int
	if err := database.QueryRow(`SELECT COALESCE(MAX(version),0) FROM schema_migrations`).Scan(&databaseVersion); err != nil {
		_ = database.Close()
		cleanup()
		return "", nil, fmt.Errorf("read exported database version: %w", err)
	}
	var quarantinedRecords int
	if err := database.QueryRow(`SELECT COUNT(*) FROM corrupt_records`).Scan(&quarantinedRecords); err != nil {
		_ = database.Close()
		cleanup()
		return "", nil, fmt.Errorf("count quarantined records in export: %w", err)
	}
	reader := &jobStore{db: database, root: s.cfg.root}
	jobs, err := reader.loadLibraryJobs()
	if err != nil {
		_ = database.Close()
		cleanup()
		return "", nil, fmt.Errorf("read Library from exported snapshot: %w", err)
	}
	if err := database.Close(); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("close database snapshot: %w", err)
	}

	exportedAt := time.Now().UTC()
	manifest := libraryExportManifest{
		Format: "yt-dl-go-library-export", FormatVersion: libraryExportFormatVersion,
		ExportedAt: exportedAt, DatabaseVersion: databaseVersion,
		MediaIncluded: false, ContainsPrivateDB: true, QuarantinedRecordCount: quarantinedRecords,
	}
	records := make([]libraryExportRecord, 0)
	for _, job := range jobs {
		for _, file := range job.Files {
			records = append(records, libraryExportRecord{
				JobID: job.ID, URL: job.URL, Kind: job.Kind, MediaType: job.MediaType,
				Status: job.Status, Title: job.Title, CreatedAt: job.CreatedAt, Category: job.Category,
				File: exportLibraryFile(file),
			})
		}
	}
	document := libraryExportDocument{Manifest: manifest, Records: records}
	archivePath := filepath.Join(workDir, "yt-dl-go-library-export.zip")
	archiveFile, err := os.OpenFile(archivePath, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		cleanup()
		return "", nil, fmt.Errorf("create export archive: %w", err)
	}
	archive := zip.NewWriter(archiveFile)
	writeErr := addExportFile(archive, "state.db", databasePath)
	if writeErr == nil {
		writeErr = addExportJSON(archive, "manifest.json", manifest)
	}
	if writeErr == nil {
		writeErr = addExportJSON(archive, "library.json", document)
	}
	if writeErr == nil {
		writeErr = addExportCSV(archive, records)
	}
	if closeErr := archive.Close(); writeErr == nil {
		writeErr = closeErr
	}
	if closeErr := archiveFile.Close(); writeErr == nil {
		writeErr = closeErr
	}
	if writeErr != nil {
		cleanup()
		return "", nil, fmt.Errorf("write Library export archive: %w", writeErr)
	}
	return archivePath, cleanup, nil
}

func sqliteReadOnlyDSN(path string) (string, error) {
	absPath, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve snapshot path: %w", err)
	}
	query := url.Values{}
	query.Set("mode", "ro")
	query.Add("_pragma", "query_only(ON)")
	if filepath.VolumeName(absPath) != "" {
		return "file:" + url.PathEscape(absPath) + "?" + query.Encode(), nil
	}
	return (&url.URL{Scheme: "file", Path: filepath.ToSlash(absPath), RawQuery: query.Encode()}).String(), nil
}

func exportLibraryFile(file mediaFile) libraryExportFile {
	exported := libraryExportFile{
		ID: file.ID, Name: file.Name, Size: file.Size, Height: file.Height, MimeType: file.MimeType,
		Title: file.Title, Author: file.Author, DurationSeconds: file.DurationSeconds, ThumbnailURL: file.ThumbnailURL,
		PublishDate: file.PublishDate, Category: file.Category, OutputRelativePath: filepath.ToSlash(file.OutputRelativePath),
		ManagedAvailable: file.ManagedAvailable, PublishedAvailable: file.PublishedAvailable,
		Chapters: append([]mediaChapter(nil), file.Chapters...), SourceItemIndex: file.SourceItemIndex,
		ChapterIndex: file.ChapterIndex, ChapterTitle: file.ChapterTitle,
	}
	if file.Subtitle != nil {
		exported.Subtitle = &libraryExportSubtitle{
			LanguageCode: file.Subtitle.LanguageCode, Label: file.Subtitle.Label, Format: file.Subtitle.Format,
			AutoGenerated: file.Subtitle.AutoGenerated, Name: file.Subtitle.Name, Size: file.Subtitle.Size,
			OutputRelativePath: filepath.ToSlash(file.Subtitle.OutputRelativePath), ManagedAvailable: file.Subtitle.ManagedAvailable,
			PublishedAvailable: file.Subtitle.PublishedAvailable,
		}
	}
	return exported
}

func addExportJSON(archive *zip.Writer, name string, value any) error {
	entry, err := archive.Create(name)
	if err != nil {
		return err
	}
	encoder := json.NewEncoder(entry)
	encoder.SetIndent("", "  ")
	return encoder.Encode(value)
}

func addExportFile(archive *zip.Writer, name, path string) error {
	entry, err := archive.Create(name)
	if err != nil {
		return err
	}
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer func() { _ = file.Close() }()
	_, err = io.Copy(entry, file)
	return err
}

func addExportCSV(archive *zip.Writer, records []libraryExportRecord) error {
	entry, err := archive.Create("library.csv")
	if err != nil {
		return err
	}
	writer := csv.NewWriter(entry)
	if err := writer.Write([]string{
		"jobId", "url", "kind", "mediaType", "status", "title", "createdAt", "category",
		"fileId", "fileName", "mimeType", "size", "height", "fileTitle", "author", "durationSeconds",
		"publishDate", "fileCategory", "outputRelativePath", "managedAvailable", "publishedAvailable",
		"subtitleLanguage", "subtitleFormat", "subtitleName", "subtitleSize", "subtitleRelativePath",
		"subtitleManagedAvailable", "subtitlePublishedAvailable", "sourceItemIndex", "chapterIndex", "chapterTitle",
	}); err != nil {
		return err
	}
	for _, record := range records {
		file := record.File
		subtitle := file.Subtitle
		var language, format, name, size, relativePath, managed, published string
		if subtitle != nil {
			language, format, name = subtitle.LanguageCode, subtitle.Format, subtitle.Name
			size = strconv.FormatInt(subtitle.Size, 10)
			relativePath = subtitle.OutputRelativePath
			managed = strconv.FormatBool(subtitle.ManagedAvailable)
			published = strconv.FormatBool(subtitle.PublishedAvailable)
		}
		row := []string{
			record.JobID, record.URL, record.Kind, record.MediaType, record.Status, record.Title, record.CreatedAt, record.Category,
			file.ID, file.Name, file.MimeType, strconv.FormatInt(file.Size, 10), strconv.Itoa(file.Height), file.Title,
			file.Author, strconv.FormatInt(file.DurationSeconds, 10), file.PublishDate, file.Category, file.OutputRelativePath,
			strconv.FormatBool(file.ManagedAvailable), strconv.FormatBool(file.PublishedAvailable), language, format, name, size,
			relativePath, managed, published, strconv.Itoa(file.SourceItemIndex), strconv.Itoa(file.ChapterIndex), file.ChapterTitle,
		}
		for index := range row {
			row[index] = safeCSVCell(row[index])
		}
		if err := writer.Write(row); err != nil {
			return err
		}
	}
	writer.Flush()
	return writer.Error()
}

func safeCSVCell(value string) string {
	trimmed := strings.TrimLeft(value, " \t\r\n")
	if trimmed != "" && strings.ContainsRune("=+-@", rune(trimmed[0])) {
		return "'" + value
	}
	return value
}
