package main

import (
	"strings"
	"testing"

	"github.com/kkdai/youtube/v2"
)

func captionTrack(code, label, kind, baseURL string) youtube.CaptionTrack {
	var track youtube.CaptionTrack
	track.LanguageCode = code
	track.Name.SimpleText = label
	track.Kind = kind
	track.BaseURL = baseURL
	return track
}

func TestInspectedCaptionTracksPrefersManual(t *testing.T) {
	video := &youtube.Video{CaptionTracks: []youtube.CaptionTrack{
		captionTrack("en", "English (auto-generated)", "asr", "https://www.youtube.com/api/timedtext?v=x&lang=en"),
		captionTrack("en", "English", "", "https://www.youtube.com/api/timedtext?v=x&lang=en"),
		captionTrack("es", "Spanish", "", "https://www.youtube.com/api/timedtext?v=x&lang=es"),
		captionTrack("../bad", "Bad", "", "https://www.youtube.com/api/timedtext?v=x"),
	}}
	tracks := inspectedCaptionTracks(video)
	if len(tracks) != 2 || tracks[0].LanguageCode != "en" || tracks[0].Label != "English" || tracks[0].AutoGenerated || tracks[1].LanguageCode != "es" {
		t.Fatalf("unexpected inspected captions: %+v", tracks)
	}
}

func TestCaptionURLValidation(t *testing.T) {
	u, err := captionURL("https://www.youtube.com/api/timedtext?v=abc&lang=en")
	if err != nil || u.Query().Get("fmt") != "vtt" {
		t.Fatalf("valid caption URL rejected: %v %v", u, err)
	}
	for _, raw := range []string{
		"http://www.youtube.com/api/timedtext?v=abc",
		"https://evil.example/api/timedtext?v=abc",
		"https://www.youtube.com/watch?v=abc",
		"https://user@www.youtube.com/api/timedtext?v=abc",
	} {
		if _, err := captionURL(raw); err == nil {
			t.Fatalf("unsafe caption URL accepted: %s", raw)
		}
	}
}

func TestWebVTTToSRT(t *testing.T) {
	input := []byte("WEBVTT\n\n00:00.500 --> 00:02.000 align:start\nHello\nworld\n\ncue-2\n01:02:03.004 --> 01:02:05.006\nSecond cue\n")
	output, err := webVTTToSRT(input)
	if err != nil {
		t.Fatal(err)
	}
	text := string(output)
	for _, expected := range []string{
		"1\n00:00:00,500 --> 00:00:02,000\nHello\nworld",
		"2\n01:02:03,004 --> 01:02:05,006\nSecond cue",
	} {
		if !strings.Contains(text, expected) {
			t.Fatalf("SRT output missing %q:\n%s", expected, text)
		}
	}
}

func TestValidateSubtitleRequest(t *testing.T) {
	for _, valid := range [][2]string{{"", ""}, {"en", "vtt"}, {"pt-BR", "srt"}, {"es-419", "vtt"}} {
		if err := validateSubtitleRequest(valid[0], valid[1]); err != nil {
			t.Fatalf("valid request rejected: %v", err)
		}
	}
	for _, invalid := range [][2]string{{"", "vtt"}, {"../en", "vtt"}, {"en", "txt"}, {"english", "srt"}} {
		if err := validateSubtitleRequest(invalid[0], invalid[1]); err == nil {
			t.Fatalf("invalid request accepted: %#v", invalid)
		}
	}
}
