package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/kkdai/youtube/v2"
)

const maxCaptionBytes int64 = 5 * 1024 * 1024

type captionFetcher func(context.Context, youtube.CaptionTrack, string) ([]byte, error)

var captionLanguageCode = regexp.MustCompile(`^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$`)
var vttTimestamp = regexp.MustCompile(`^(?:(\d+):)?(\d{2}):(\d{2})[.,](\d{3})$`)

type inspectedCaptionTrack struct {
	LanguageCode  string `json:"languageCode"`
	Label         string `json:"label"`
	AutoGenerated bool   `json:"autoGenerated,omitempty"`
}

type subtitleFile struct {
	LanguageCode       string `json:"languageCode"`
	Label              string `json:"label,omitempty"`
	Format             string `json:"format"`
	AutoGenerated      bool   `json:"autoGenerated,omitempty"`
	Name               string `json:"name"`
	Size               int64  `json:"size"`
	OutputName         string `json:"outputName,omitempty"`
	OutputPath         string `json:"-"`
	OutputRelativePath string `json:"outputRelativePath,omitempty"`
	ManagedAvailable   bool   `json:"managedAvailable"`
	PublishedAvailable bool   `json:"publishedAvailable"`
}

func validateSubtitleRequest(language, format string) error {
	language = strings.TrimSpace(language)
	format = strings.ToLower(strings.TrimSpace(format))
	if language == "" {
		if format != "" {
			return errors.New("subtitleFormat requires subtitleLanguage")
		}
		return nil
	}
	if !captionLanguageCode.MatchString(language) {
		return errors.New("subtitleLanguage must be a valid caption language code")
	}
	if format != "vtt" && format != "srt" {
		return errors.New("subtitleFormat must be vtt or srt when subtitles are enabled")
	}
	return nil
}

func inspectedCaptionTracks(video *youtube.Video) []inspectedCaptionTrack {
	if video == nil {
		return nil
	}
	// Prefer a creator-provided track over ASR when YouTube exposes both for
	// the same language, while preserving the upstream order otherwise.
	byLanguage := map[string]youtube.CaptionTrack{}
	order := []string{}
	for _, track := range video.CaptionTracks {
		code := strings.TrimSpace(track.LanguageCode)
		if !captionLanguageCode.MatchString(code) || strings.TrimSpace(track.BaseURL) == "" {
			continue
		}
		key := strings.ToLower(code)
		current, exists := byLanguage[key]
		if !exists {
			order = append(order, key)
			byLanguage[key] = track
			continue
		}
		if current.Kind == "asr" && track.Kind != "asr" {
			byLanguage[key] = track
		}
	}
	result := make([]inspectedCaptionTrack, 0, len(order))
	for _, key := range order {
		track := byLanguage[key]
		label := strings.TrimSpace(track.Name.SimpleText)
		if label == "" {
			label = track.LanguageCode
		}
		result = append(result, inspectedCaptionTrack{
			LanguageCode:  track.LanguageCode,
			Label:         label,
			AutoGenerated: track.Kind == "asr",
		})
	}
	return result
}

func selectCaptionTrack(video *youtube.Video, language string) (youtube.CaptionTrack, bool) {
	if video == nil {
		return youtube.CaptionTrack{}, false
	}
	var fallback *youtube.CaptionTrack
	for i := range video.CaptionTracks {
		track := &video.CaptionTracks[i]
		if !strings.EqualFold(strings.TrimSpace(track.LanguageCode), strings.TrimSpace(language)) {
			continue
		}
		if track.Kind != "asr" {
			return *track, true
		}
		if fallback == nil {
			fallback = track
		}
	}
	if fallback != nil {
		return *fallback, true
	}
	return youtube.CaptionTrack{}, false
}

func captionURL(raw string) (*url.URL, error) {
	u, err := url.Parse(raw)
	if err != nil || u.Scheme != "https" || u.User != nil || u.Opaque != "" || (u.Port() != "" && u.Port() != "443") {
		return nil, errors.New("caption track URL is invalid")
	}
	host := strings.ToLower(u.Hostname())
	if host != "youtube.com" && host != "www.youtube.com" && host != "m.youtube.com" && host != "music.youtube.com" {
		return nil, errors.New("caption track URL is not hosted by YouTube")
	}
	if u.Path != "/api/timedtext" {
		return nil, errors.New("caption track URL is not a YouTube timed-text endpoint")
	}
	query := u.Query()
	query.Set("fmt", "vtt")
	u.RawQuery = query.Encode()
	return u, nil
}

func (s *server) fetchCaptionTrack(ctx context.Context, track youtube.CaptionTrack, format string) ([]byte, error) {
	u, err := captionURL(track.BaseURL)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", youtube.AndroidClient.UserAgent)
	timeout := 30 * time.Second
	if s.cfg.timeout > 0 {
		timeout = min(s.cfg.timeout, timeout)
	}
	client := nativeHTTPClient(timeout)
	client.CheckRedirect = func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("caption endpoint returned HTTP %d", resp.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, maxCaptionBytes+1))
	if err != nil || len(body) == 0 || int64(len(body)) > maxCaptionBytes {
		return nil, errors.New("caption response is empty or exceeds the 5 MiB limit")
	}
	body = bytes.TrimPrefix(body, []byte{0xef, 0xbb, 0xbf})
	if !strings.HasPrefix(strings.TrimSpace(string(body)), "WEBVTT") {
		return nil, errors.New("caption response is not valid WebVTT")
	}
	if format == "srt" {
		return webVTTToSRT(body)
	}
	return body, nil
}

func subtitleTimestamp(value string) (string, error) {
	match := vttTimestamp.FindStringSubmatch(strings.TrimSpace(value))
	if match == nil {
		return "", errors.New("invalid WebVTT cue timestamp")
	}
	hours := 0
	if match[1] != "" {
		parsed, err := strconv.Atoi(match[1])
		if err != nil {
			return "", err
		}
		hours = parsed
	}
	minutes, _ := strconv.Atoi(match[2])
	seconds, _ := strconv.Atoi(match[3])
	if minutes > 59 || seconds > 59 {
		return "", errors.New("invalid WebVTT cue timestamp")
	}
	return fmt.Sprintf("%02d:%02d:%02d,%s", hours, minutes, seconds, match[4]), nil
}

func webVTTToSRT(input []byte) ([]byte, error) {
	text := strings.ReplaceAll(strings.ReplaceAll(string(input), "\r\n", "\n"), "\r", "\n")
	if !strings.HasPrefix(strings.TrimSpace(text), "WEBVTT") {
		return nil, errors.New("caption response is not valid WebVTT")
	}
	blocks := regexp.MustCompile(`\n[ \t]*\n`).Split(text, -1)
	var output strings.Builder
	cue := 0
	for _, block := range blocks {
		lines := strings.Split(strings.TrimSpace(block), "\n")
		if len(lines) == 0 || strings.HasPrefix(lines[0], "WEBVTT") || strings.HasPrefix(lines[0], "NOTE") || strings.HasPrefix(lines[0], "STYLE") || strings.HasPrefix(lines[0], "REGION") {
			continue
		}
		timeLine := -1
		for i, line := range lines {
			if strings.Contains(line, "-->") {
				timeLine = i
				break
			}
		}
		if timeLine < 0 || timeLine+1 >= len(lines) {
			continue
		}
		parts := strings.SplitN(lines[timeLine], "-->", 2)
		if len(parts) != 2 {
			continue
		}
		endToken := strings.Fields(strings.TrimSpace(parts[1]))
		if len(endToken) == 0 {
			continue
		}
		start, err := subtitleTimestamp(parts[0])
		if err != nil {
			return nil, err
		}
		end, err := subtitleTimestamp(endToken[0])
		if err != nil {
			return nil, err
		}
		cue++
		fmt.Fprintf(&output, "%d\n%s --> %s\n", cue, start, end)
		output.WriteString(strings.Join(lines[timeLine+1:], "\n"))
		output.WriteString("\n\n")
	}
	if cue == 0 {
		return nil, errors.New("WebVTT contained no usable caption cues")
	}
	return []byte(output.String()), nil
}

func (s *server) captureSubtitle(ctx context.Context, j *jobState, file *mediaFile, video *youtube.Video, budget int64) int64 {
	if j.SubtitleLanguage == "" || j.SubtitleFormat == "" || budget <= 0 {
		return 0
	}
	track, ok := selectCaptionTrack(video, j.SubtitleLanguage)
	if !ok {
		file.SubtitleError = "Selected caption language is unavailable for this item"
		return 0
	}
	fetch := s.captionFetcher
	var data []byte
	var err error
	if fetch != nil {
		data, err = fetch(ctx, track, j.SubtitleFormat)
	} else {
		data, err = s.fetchCaptionTrack(ctx, track, j.SubtitleFormat)
	}
	if err != nil {
		file.SubtitleError = "Caption sidecar could not be downloaded"
		return 0
	}
	if int64(len(data)) > budget || int64(len(data)) > maxCaptionBytes {
		file.SubtitleError = "Caption sidecar exceeds the remaining job storage limit"
		return 0
	}
	code := strings.ToLower(strings.TrimSpace(track.LanguageCode))
	name := strings.TrimSuffix(file.Name, filepath.Ext(file.Name)) + "." + code + "." + j.SubtitleFormat
	path := filepath.Join(j.dir, name)
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		file.SubtitleError = "Caption sidecar could not be stored"
		return 0
	}
	part := path + ".part"
	_ = os.Remove(part)
	out, err := os.OpenFile(part, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		file.SubtitleError = "Caption sidecar could not be stored"
		return 0
	}
	written, writeErr := out.Write(data)
	if writeErr != nil || written != len(data) {
		_ = out.Close()
		_ = os.Remove(part)
		file.SubtitleError = "Caption sidecar could not be stored"
		return 0
	}
	if err := syncCloseRename(out, part, path); err != nil {
		_ = os.Remove(part)
		file.SubtitleError = "Caption sidecar could not be stored"
		return 0
	}
	label := strings.TrimSpace(track.Name.SimpleText)
	if label == "" {
		label = track.LanguageCode
	}
	file.Subtitle = &subtitleFile{
		LanguageCode:     track.LanguageCode,
		Label:            label,
		Format:           j.SubtitleFormat,
		AutoGenerated:    track.Kind == "asr",
		Name:             name,
		Size:             int64(len(data)),
		ManagedAvailable: true,
	}
	file.SubtitleError = ""
	return int64(len(data))
}

func openSubtitleManaged(dir string, subtitle subtitleFile) (*os.File, error) {
	if err := validateSubtitleManagedName(subtitle.Name, subtitle.Format); err != nil {
		return nil, err
	}
	path := filepath.Join(dir, subtitle.Name)
	before, err := os.Lstat(path)
	if err != nil || !before.Mode().IsRegular() || before.Size() != subtitle.Size || before.Size() <= 0 {
		return nil, errors.New("caption sidecar unavailable")
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, errors.New("caption sidecar unavailable")
	}
	after, err := file.Stat()
	if err != nil || !os.SameFile(before, after) {
		_ = file.Close()
		return nil, errors.New("caption sidecar changed")
	}
	return file, nil
}

func publishSubtitleOutput(j *jobState, file *mediaFile) error {
	if file.Subtitle == nil || !file.Subtitle.ManagedAvailable || !file.PublishedAvailable {
		return nil
	}
	subtitle := file.Subtitle
	source, err := openSubtitleManaged(j.dir, *subtitle)
	if err != nil {
		return err
	}
	base := strings.TrimSuffix(file.OutputName, filepath.Ext(file.OutputName))
	name := base + "." + strings.ToLower(subtitle.LanguageCode) + "." + subtitle.Format
	destination := filepath.Join(filepath.Dir(file.OutputPath), name)
	temporaryPath, copyErr := writeTemporaryCopy(source, filepath.Dir(destination), ".yt-dl-go-caption-*.part", subtitle.Size)
	sourceCloseErr := source.Close()
	if copyErr != nil || sourceCloseErr != nil {
		_ = os.Remove(temporaryPath)
		return errors.Join(errors.New("could not write caption sidecar"), sourceCloseErr)
	}
	if err := publishTemporary(temporaryPath, destination); err != nil {
		_ = os.Remove(temporaryPath)
		return err
	}
	subtitle.OutputName = name
	subtitle.OutputPath = destination
	relativeDir := filepath.Dir(filepath.FromSlash(file.OutputRelativePath))
	if relativeDir == "." {
		subtitle.OutputRelativePath = name
	} else {
		subtitle.OutputRelativePath = filepath.ToSlash(filepath.Join(relativeDir, name))
	}
	subtitle.PublishedAvailable = true
	return nil
}

func validateSubtitleManagedName(name, format string) error {
	if filepath.Base(name) != name || (format != "vtt" && format != "srt") || filepath.Ext(name) != "."+format {
		return errors.New("job contains invalid caption sidecar metadata")
	}
	return nil
}
